<div class="container">	
		<div class="row">
			<div id="col1" class="col-sm-12">
            	 <footer class="footer-distributed">
						
			<div class="footer-left">

				<p class="footer-links">
					<a href="index.php">New Arrival</a>
					--
					<a href="men page.php">Men</a>
					--
					<a href="women page.php">Women</a>
					--
					<a href="#">Children</a>
					--
					<a href="brand.php">Brands</a>
					--
					<a href="feedback.php">Feedback</a>
					--
					<a href="enquiry.php">enquiry</a>
				</p>

				<p>Sports WareHouse &copy; 2019</p>
			</div></div></div></div></div></footer>