<nav class="container navbar navbar-expand-lg bg-dark navbar-dark" style="border-radius: 7px;">
    	<span class="navbar-brand"  style= "margin-right:35%; font-size:26px" onclick="location='file:///H:/work/tri%203/site%20work/index.php'">
Sports WareHouse
</span>


        	
         
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        	<div class="collapse navbar-collapse" id="collapsibleNavbar" >
            <!-- md-auto: left, ml-auto: right, mx-auto: center -->
            <ul class="navbar-nav" >
                <li class="nav-item">
                	<a class="nav-link" href="index.php" id="0" onClick="nav_item_selected(0)">New Arrival</a>
                 </li>
                 <li class="nav-item">
                    <a class="nav-link" href="men page.php" id="2" onClick="nav_item_selected(1)">Men</a></li>
                     <li class="nav-item">
                    <a class="nav-link" href="women page.php" id="3" onClick="nav_item_selected(2)">Women</a></li>
                    
                <!-- Dropdown -->
                <li class=" dropdown">
                    <a class="nav-link " href="#" id="3" onhover="nav_item_selected(3)" data-toggle="dropdown">
                        Children
                    </a>
                    <div class="dropdown-content">
                        <a class="dropdown-item" href="#">Below 5 yr	</a>
                        <a class="dropdown-item" href="#">Under 5 to 14 yr</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="brand.php" id="4" onClick="nav_item_selected(4)">Brands</a>
                </li>
                  <li class=" dropdown">
                    <a class="nav-link " href="#" id="3" onhover="nav_item_selected(3)" data-toggle="dropdown">
                       Contact Us
                    </a>
                    <div class="dropdown-content">
                        <a class="dropdown-item" href="feedback.php">Feedback	</a>
                        <a class="dropdown-item" href="enquiry.php">Enquiry</a>
                    </div>
                </li>


                
            </ul>
        </div>
        
        

        
    </nav><br>